version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: drugtracker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drugtracker_db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
